name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: npm ci
      - run: npm run build
      - run: npm run build -- --minify
      - uses: actions/upload-artifact@v3
        with:
          name: MZFM_I18n.js
          path: dist/MZFM_I18n.js
      - uses: actions/upload-artifact@v3
        with:
          name: MZFM_I18n.min.js
          path: dist/MZFM_I18n.min.js
